### ISSUE TITLE
Running tests with least privlege

### ISSUE THREAD

**Issue by kjacobsen** [PowerShell/DscResource.Tests#66] opened 2016-07-17 06:44 UTC
Hi,

When running in an environment of least privilege, you cannot run DSC tests making use of TestHelper.psm1.

The helper attempts to make registry changes on line 373. My analysis seems to show that we don't need to make this change at a system level, for all future executions of PowerShell. My recommendation is to remove like 373. If removal cannot occur, then place the correct # requires statement to ensure that it is executed as an Administrator.

The script modifies the execution policy. Once again this creates issues on multiple levels. This logic should be removed, and recommendations made on how the environment should be setup.

There is also calls to install-module that need to be addressed as well.

**Comment by PlagueHO** [comment] 2016-07-17 19:50
Hi there. The reason for the system level changes to the PSModulePath is so that the integration tests can run. The LCM runs under a different context than the user initiating the tests. So this is currently the only way to ensure that the module being integration tested can be found. 

That being said,  this isn't necessary for unit tests. There is already an issue open for correcting this.

**Comment by PlagueHO** [comment] 2016-07-17 19:52
Issue #58 is the one open for resolving this. Feel free to submit a PR For it :smile:

**Comment by KarolKaczmarek** [comment] 2016-07-19 00:56
Thanks for feedback, as @PlagueHO noticed, this is duplicate of #58, so I'll close it for now.
Feel free to reply in #58 if you have further comments.
Thanks!

**Closed by KarolKaczmarek** 2016-07-19 00:56 UTC
